<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5e7d1d9248039',
	'title' => 'Alert Options',
	'fields' => array(
		array(
			'key' => 'field_5e7d1da808a4a',
			'label' => 'Activate Alert',
			'name' => 'activate_alert',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'On',
			'ui_off_text' => 'Off',
		),
		array(
			'key' => 'field_5e7d1dd808a4b',
			'label' => 'Alert Text',
			'name' => 'alert_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 2,
			'new_lines' => 'wpautop',
		),
		array(
			'key' => 'field_5e7d1dfe08a4c',
			'label' => 'Alert Button',
			'name' => 'alert_button',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_5e7d1e0508a4d',
			'label' => 'Alert Delay',
			'name' => 'alert_delay',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'seconds',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5e7e576793dc7',
			'label' => 'Alert Background Color',
			'name' => 'alert_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5e7d1e2208a4e',
			'label' => 'Cookie ID',
			'name' => 'cookie_id',
			'type' => 'text',
			'instructions' => 'Change this whenever you change the alert. It doesn\'t matter what it is, it just has to be filled out, and has to be different from the last alert. This sets a new cookie, which lets us know they\'ve already closed the alert, so we don\'t need to show them again. When you change this, it sets a new cookie so it will show up to users who closed the last alert recently.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-alert',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;